GET http://localhost:5001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWxpYXMiLCJpYXQiOjE2NTQxMTU5MjF9.9GVXfxRCdXDDYl1WnZpnNR2VbwhHdgOB_WXZrm6zUMk
###

POST http://localhost:5001/login
Content-Type: application/json

{
    "username": "elias"
}

